"""Modulo para la definicion de los campos de la funcionalidad de clientes."""

from enum import StrEnum
from dataclasses import dataclass, field as dataclass_field

class ClientField(StrEnum):
    """Mapeo de campos o nombre de las columnas de los clientes."""
    TIPOIDENTIFICACION = "TIPOIDENTIFICACION"
    NUMERODOCUMENTO = "NUMERODOCUMENTO"
    DV = "DV"
    CODIGOALTERNO1 = "CODIGOALTERNO1"
    CODIGOALTERNO2 = "CODIGOALTERNO2"
    CODIGOEANLOCALIZACION = "CODIGOEANLOCALIZACION"
    CODIGOPOSTAL = "CODIGOPOSTAL"
    NOMBRERAZONSOCIAL = "NOMBRERAZONSOCIAL"
    NOMBRE2 = "NOMBRE2"
    APELLIDO1 = "APELLIDO1"
    APELLIDO2 = "APELLIDO2"
    RAZONSOCIALNOMBRES = "RAZONSOCIALNOMBRES"
    NOMBRECOMERCIALAPELLIDOS = "NOMBRECOMERCIALAPELLIDOS"
    SEXO = "SEXO"
    CLIENTE = "CLIENTE"
    PROVEEDOR = "PROVEEDOR"
    VENDEDOR = "VENDEDOR"
    TRANSPORTADOR = "TRANSPORTADOR"
    EMPLEADO = "EMPLEADO"
    BANCO = "BANCO"
    ASEGURADORA = "ASEGURADORA"
    PROPIETARIO = "PROPIETARIO"
    INQUILINO = "INQUILINO"
    DEUDOR = "DEUDOR"
    ADMSALUD = "ADMSALUD"
    ADMPENSION = "ADMPENSION"
    ADMRIESGOS = "ADMRIESGOS"
    CAJA = "CAJA"
    FCESANTIAS = "FCESANTIAS"
    SOCIO = "SOCIO"
    MIEMPRESA = "MIEMPRESA"
    SUCURSAL = "SUCURSAL"
    SIA = "SIA"
    CAJEROPOS = "CAJEROPOS"
    HOTEL = "HOTEL"
    AEROLINEA = "AEROLINEA"
    AGVIAJE = "AGVIAJE"
    SERVNOMINA = "SERVNOMINA"
    VIAPRINCIPAL = "VIAPRINCIPAL"
    NOPRI = "NOPRI"
    NOMENCLATURAPRI = "NOMENCLATURAPRI"
    CARDINALIDADPRI = "CARDINALIDADPRI"
    VIASECUNDARIA = "VIASECUNDARIA"
    NOSEC = "NOSEC"
    NOMENCLATURASEC = "NOMENCLATURASEC"
    CARDINALIDADSEC = "CARDINALIDADSEC"
    PLACA = "PLACA"
    COMPLEMENTO = "COMPLEMENTO"
    FORMULADIRECCION = "FORMULADIRECCION"
    VIAPRINCIPALMM = "VIAPRINCIPALMM"
    NOPRIMM = "NOPRIMM"
    NOMENCLATURAPRIMM = "NOMENCLATURAPRIMM"
    CARDINALIDADPRIMM = "CARDINALIDADPRIMM"
    VIASECUNDARIAMM = "VIASECUNDARIAMM"
    NOSECMM = "NOSECMM"
    NOMENCLATURASECMM = "NOMENCLATURASECMM"
    CARDINALIDADSECMM = "CARDINALIDADSECMM"
    PLACAMM = "PLACAMM"
    COMPLEMENTOMM = "COMPLEMENTOMM"
    FORMULADIRECCIONMM = "FORMULADIRECCIONMM"
    CODIGOCIUDAD = "CODIGOCIUDAD"
    TELEFONO1 = "TELEFONO1"
    TELEFONO2 = "TELEFONO2"
    TELEFONOMOVIL = "TELEFONOMOVIL"
    FAX = "FAX"
    CORREOSELECTRONICOS = "CORREOSELECTRONICOS"
    PAGINAWEB = "PAGINAWEB"
    FECHADENACIMIENTO = "FECHADENACIMIENTO"
    FECHADECREACION = "FECHADECREACION"
    LONGITUDCODIGOSSCC = "LONGITUDCODIGOSSCC"
    ESTADO = "ESTADO"
    CODIGOLISTADEPRECIOS = "CODIGOLISTADEPRECIOS"
    CODIGODOCUMENTOVENDEDOR = "CODIGODOCUMENTOVENDEDOR"
    CODIGODOCUMENTOASOCIADO = "CODIGODOCUMENTOASOCIADO"
    CODIGOCLASIFICACION = "CODIGOCLASIFICACION"
    MACROCANAL = "MACROCANAL"
    CENTRODECOSTO = "CENTRODECOSTO"
    ZONA = "ZONA"
    CUPOASIGNADO = "CUPOASIGNADO"
    PUNTOSACUMULADOS = "PUNTOSACUMULADOS"
    PRESUPUESTOYEAR = "PRESUPUESTOYEAR"
    DESCUENTOCOMERCIAL = "DESCUENTOCOMERCIAL"
    DESCUENTOFINANCIERO = "DESCUENTOFINANCIERO"
    CODIGOFORMADEPAGOVENTA = "CODIGOFORMADEPAGOVENTA"
    CODIGOFORMADEPAGOCOMPRA = "CODIGOFORMADEPAGOCOMPRA"
    ESAGENTERETENEDOR = "ESAGENTERETENEDOR"
    ESAUTORETENEDORRENTA = "ESAUTORETENEDORRENTA"
    ESAUTORETENEDORDEIVA = "ESAUTORETENEDORDEIVA"
    ESAUTORETENEDORICA = "ESAUTORETENEDORICA"
    ESAUTORETENEDORCREE = "ESAUTORETENEDORCREE"
    ESGRANCONTRIBUYENTE = "ESGRANCONTRIBUYENTE"
    COMPRACI = "COMPRACI"
    ESENTIDADESTATAL = "ESENTIDADESTATAL"
    NORESPONSABLEIVA = "NORESPONSABLEIVA"
    PERTENECEALREGIMENSIMPLE = "PERTENECEALREGIMENSIMPLE"
    ACOGIDOLEYREORGANIZACION = "ACOGIDOLEYREORGANIZACION"
    REGIMENVENTAS = "REGIMENVENTAS"
    CODIGONATURALEZAJURIDICA = "CODIGONATURALEZAJURIDICA"
    CODIGOACTIVIDADECONOMICA = "CODIGOACTIVIDADECONOMICA"
    CODIGOCLASIFICACIONRENTA = "CODIGOCLASIFICACIONRENTA"
    CERTIFICADODELADIAN = "CERTIFICADODELADIAN"
    IVAPROVEEDOR = "IVAPROVEEDOR"
    IVACLIENTE = "IVACLIENTE"
    IMPOCONSUMOPROVEEDOR = "IMPOCONSUMOPROVEEDOR"
    IMPOCONSUMOCLIENTE = "IMPOCONSUMOCLIENTE"
    RETEFUENTEPROVEEDOR = "RETEFUENTEPROVEEDOR"
    RETEFUENTEPROVEEDORBASE0 = "RETEFUENTEPROVEEDORBASE0"
    RETEFUENTECLIENTE = "RETEFUENTECLIENTE"
    RETEFUENTECLIENTEBASE0 = "RETEFUENTECLIENTEBASE0"
    RETEIVAPROVEEDOR = "RETEIVAPROVEEDOR"
    RETEIVAPROVEEDORBASE0 = "RETEIVAPROVEEDORBASE0"
    RETEIVACLIENTE = "RETEIVACLIENTE"
    RETEIVACLIENTEBASE0 = "RETEIVACLIENTEBASE0"
    RETEICAPROVEEDOR = "RETEICAPROVEEDOR"
    RETEICAPROVEEDORBASE0 = "RETEICAPROVEEDORBASE0"
    RETEICACLIENTE = "RETEICACLIENTE"
    RETEICACLIENTEBASE0 = "RETEICACLIENTEBASE0"
    RETECREEPROVEEDOR = "RETECREEPROVEEDOR"
    RETECREEPROVEEDORBASE0 = "RETECREEPROVEEDORBASE0"
    RETECREECLIENTE = "RETECREECLIENTE"
    RETECREECLIENTEBASE0 = "RETECREECLIENTEBASE0"
    NUMERODOCUMENTOCONTACTO = "NUMERODOCUMENTOCONTACTO"
    CODIGOALTERNOCONTACTO = "CODIGOALTERNOCONTACTO"
    NOMBRECONTACTO = "NOMBRECONTACTO"
    CARGOCONTACTO = "CARGOCONTACTO"
    TELEFONOCONTACTO = "TELEFONOCONTACTO"
    TELEFONOMOVILCONTACTO = "TELEFONOMOVILCONTACTO"
    CORREOCONTACTO = "CORREOCONTACTO"
    COMERCIALCONTACTO = "COMERCIALCONTACTO"
    ADMINISTRATIVOCONTACTO = "ADMINISTRATIVOCONTACTO"
    CONTABLECONTACTO = "CONTABLECONTACTO"
    DOCUMENTOEQUIVALENTECONTACTO = "DOCUMENTOEQUIVALENTECONTACTO"
    CERTIFICADOPROVEEDORCONTACTO = "CERTIFICADOPROVEEDORCONTACTO"
    CONTRATOLABORALCONTACTO = "CONTRATOLABORALCONTACTO"
    CARTERACONTACTO = "CARTERACONTACTO"
    FACTURACIONELECTRONICACONTACTO = "FACTURACIONELECTRONICACONTACTO"
    CAMPOLIBRE = "CAMPOLIBRE"
    CAMPOLIBRE2 = "CAMPOLIBRE2"
    CAMPOLIBRE3 = "CAMPOLIBRE3"
    PAIS = "PAIS"
    DEPARTAMENTO = "DEPARTAMENTO"
    DIVISA = "DIVISA"

class ClientFieldShopifyMx(StrEnum):
    """Mapeo de campos o nombre de las columnas de los clientes de Shopify App Matrixify."""
    ID = "ID"
    EMAIL = "Email"
    FIRST_NAME = "First Name"
    SECOND_NAME = "Second Name"
    LAST_NAME = "Last Name"
    SECOND_LAST_NAME = "Second Last Name"
    PHONE = "Phone"
    CREATED_AT = "Created At"
    ADDRESS_ID = "Address ID"
    ADDRESS_PHONE = "Address Phone"
    ADDRESS_COMPANY = "Address Company"
    ADDRESS_LINE_1 = "Address Line 1"
    ADDRESS_LINE_2 = "Address Line 2"
    ADDRESS_CITY = "Address City"
    ADDRESS_PROVINCE = "Address Province"
    ADDRESS_COUNTRY = "Address Country"
    ADDRESS_ZIP = "Address Zip"
    ADDRESS_IS_DEFAULT = "Address Is Default"
    MF_TIPO_DE_DOCUMENTO = "Metafield: custom.tipo_de_documento [single_line_text_field]"

@dataclass
class ClientShopifyJsonAddress:
    """Direccion de los clientes en formato JSON mediante la API de Shopify. Version: 2024-01"""
    id: int
    customer_id: int
    first_name: str
    last_name: str
    company: str
    address1: str
    address2: str
    city: str
    province: str
    country: str
    zip: str
    phone: str
    name: str
    province_code: str
    country_code: str
    country_name: str
    default: bool

@dataclass
class ClientShopifyJsonMetaField:
    """Metacampos de los clientes en formato JSON mediante la API de Shopify. Version: 2024-01"""
    id: int
    namespace: str # "custom"
    key: str       # "tipo_de_documento"
    value: str     # "Cédula de ciudadanía"
    owner_id: int
    type: str      # "single_line_text_field"

@dataclass
class ClientShopifyJson:
    """Informacion de los clientes en formato JSON mediante la API de Shopify. Version: 2024-01
    https://shopify.dev/docs/api/usage/versioning#release-schedule
    """
    id: int
    email: str
    created_at: str
    updated_at: str
    first_name: str
    last_name: str
    last_order_name: str
    last_order_id: int
    currency: str
    phone: str
    default_address: ClientShopifyJsonAddress
    metafields: list[ClientShopifyJsonMetaField] = dataclass_field(default_factory=list)
    